import grid2op
env = grid2op.make("l2rpn_icaps_2021_large")
env.close()
env = grid2op.make("l2rpn_icaps_2021_small")
env.close()
env = grid2op.make("l2rpn_idf_2023")
env.close()
env = grid2op.make("l2rpn_neurips_2020_track1_large")
env.close()
env = grid2op.make("l2rpn_neurips_2020_track1_small")
env.close()
env = grid2op.make("l2rpn_neurips_2020_track2_large")
env.close()
env = grid2op.make("l2rpn_neurips_2020_track2_small")
env.close()
env = grid2op.make("l2rpn_wcci_2020")
env.close()
env = grid2op.make("l2rpn_wcci_2022")
env.close()
env = grid2op.make("rte_case14_realistic")
env.close()
env = grid2op.make("rte_case14_redisp")
env.close()
env = grid2op.make("wcci_test")
env.close()
env = grid2op.make("l2rpn_case14_sandbox")
env.close()
